# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangorder',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='bangorder',
            old_name='payment_typeId',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_typeId',
            new_name='product_type',
        ),
    ]
