# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('street_address', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('state_province', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=55)),
                ('sign_up_date', models.DateField(verbose_name='sign up date')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHasProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.ManyToManyField(to='bangapi.BangOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=55)),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangapi.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangapi.ProductType'),
        ),
        migrations.AddField(
            model_name='orderhasproducts',
            name='productId',
            field=models.ManyToManyField(to='bangapi.Product'),
        ),
        migrations.AddField(
            model_name='bangorder',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangapi.Customer'),
        ),
        migrations.AddField(
            model_name='bangorder',
            name='payment_typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangapi.PaymentType'),
        ),
    ]
