# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangapi', '0002_auto_20170124_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='bangorder',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='user',
        ),
    ]
