# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangapi', '0007_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
