# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bangapi', '0008_auto_20170127_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=55)),
                ('state_province', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangapi.PaymentType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
